### ISSUE TITLE
No errors in the errors array

### ISSUE THREAD

**Issue by nixxholas** [rajanadar/VaultSharp#104]
Not sure what's going on here..

```
VaultSharp.Core.VaultApiException: {"errors":[]}

  at at VaultSharp.Core.Polymath.MakeRequestAsync[TResponse](String resourcePath, HttpMethod httpMethod, Object requestData, IDictionary`2 headers, Boolean rawResponse, Action`1 postResponseAction)
  at at VaultSharp.Core.Polymath.MakeVaultApiRequest[TResponse](String resourcePath, HttpMethod httpMethod, Object requestData, Boolean rawResponse, Action`1 postResponseAction, String wrapTimeToLive, Boolean unauthenticated)
  at at VaultSharp.V1.SecretsEngines.Cubbyhole.CubbyholeSecretsEngineProvider.ReadSecretAsync(String secretPath, String wrapTimeToLive)
  at Nozomi.Auth.Startup.ConfigureServices(IServiceCollection services) in 
```

Here's my DI.

```
var vaultToken = Configuration["vaultToken"];

                if (string.IsNullOrEmpty(vaultToken))
                    throw new SystemException("Invalid vault token.");

                var authMethod = new TokenAuthMethodInfo(vaultToken);
                var vaultClientSettings = new VaultClientSettings("http://xxxxxxx:xxxxx", authMethod);
                var vaultClient = new VaultClient(vaultClientSettings);

                var xxxxVault = vaultClient.V1.Secrets.Cubbyhole.ReadSecretAsync("xxxxx")
                    .GetAwaiter()
                    .GetResult().Data;
```

Once the last line is executed, the app goes poof and it dies.

**Comment by sethbridge** [comment]
Same here, any update?

**Comment by MrZoidberg** [comment]
You have a non-default mountPoint. To debug, add BeforeApiRequestAction and AfterApiResponseAction to VaultClientSettings to write request and response to log and you'll see the real problem.

**Comment by rajanadar** [comment]
@nixxholas  @sethbridge , this maybe a deadlock issue.
Can you try an async only test case to confirm it?
The current release has some deadlock fixes.
