### ISSUE TITLE
Method V1.Secrets.KeyValue.V2.PatchSecretAsync throw InvalidOperationException in v1.7.2

### ISSUE THREAD

**Issue by EKovalenok** [rajanadar/VaultSharp#289]
**Describe the bug**
Thow exception in Polymath.cs MakeRequestAsync method then execute PatchSecretAsync(), because cannot remove from http message headers, 'Content-Type' header.

**VaultSharp Version**
1.7.2

**Vault Version**
1.12.2

**Does this work with Vault CLI?**
Yes

**Sample Code Snippet**
Non-confidential snippet of code

**Exception Details/Stack Trace/Error Message**
```
Unhandled exception. System.AggregateException: One or more errors occurred. (Misused header name, 'Content-Type'. Make sure request headers are used with HttpRequestMessage, response headers with HttpResponseMessage, and content headers with HttpContent objects.)
 ---> System.InvalidOperationException: Misused header name, 'Content-Type'. Make sure request headers are used with HttpRequestMessage, response headers with HttpResponseMessage, and content headers with HttpContent objects.
   at System.Net.Http.Headers.HttpHeaders.GetHeaderDescriptor(String name)
   at System.Net.Http.Headers.HttpHeaders.Remove(String name)
   at VaultSharp.Core.Polymath.MakeRequestAsync[TResponse](String resourcePath, HttpMethod httpMethod, Object requestData, IDictionary`2 headers, Boolean rawResponse, Action`1 postResponseAction)
   at VaultSharp.Core.Polymath.MakeVaultApiRequest[TResponse](String resourcePath, HttpMethod httpMethod, Object requestData, Boolean rawResponse, Action`1 postResponseAction, String wrapTimeToLive, Boolean unauthenticated)
   at VaultSharp.Core.Polymath.MakeVaultApiRequest[TResponse](String mountPoint, String path, HttpMethod httpMethod, Object requestData, Boolean rawResponse, Action`1 postResponseAction, String wrapTimeToLive, Boolean unauthenticated)
   at VaultSharp.V1.SecretsEngines.KeyValue.V2.KeyValueSecretsEngineV2Provider.PatchSecretAsync(String path, PatchSecretDataRequest patchSecretDataRequest, String mountPoint)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Program.<Main>$(String[] args) in /Users/ekovalenok/Repositories/common-vault/samples/Vault.Sample/Program.cs:line 65


```
**Any additional info**
Version 1.7.1 work fine

In 1.7.2 trying remove header 'Content-Type' that does not exist in httpRequestMessage.Headers

<img width="1150" alt="Снимок экрана 2022-12-06 в 23 00 45" src="https://user-images.githubusercontent.com/8514147/206011709-524e1e8b-6eeb-4697-aa6b-cdeccebf4fbf.png">
<img width="1183" alt="Снимок экрана 2022-12-06 в 23 02 28" src="https://user-images.githubusercontent.com/8514147/206011721-c1bb0543-625a-4fe6-aa8f-e3cedbd58435.png">
<img width="1063" alt="Снимок экрана 2022-12-06 в 23 03 07" src="https://user-images.githubusercontent.com/8514147/206011729-e2722e0b-cabb-4e7f-8846-61542d51433a.png">

**Comment by rajanadar** [comment]
thanks @EKovalenok  for catching this. I'll release a fix by tomorrow. Fix in progress.

**Comment by rajanadar** [comment]
@EKovalenok  I have published a fix. Can you please try https://www.nuget.org/packages/VaultSharp/1.7.2.1 ?

**Comment by EKovalenok** [comment]
Fixed

**Comment by rajanadar** [comment]
Sweet. Thanks for verifying quickly.
