### ISSUE TITLE
Null reference exception

### ISSUE THREAD

**Issue by nkiranakumar** [rajanadar/VaultSharp#3]
Hi Rajanadar,

I was trying to work on the sample code provided by downloading the nuget package for c#, 
Below is the code. 

 IVaultClient vaultClient = VaultClientFactory.CreateVaultClient(new Uri("http://127.0.0.1:8200"),
                authenticationInfo: null);

            var path = "cubbyhole/foo/Test4321";

            var secretData = new Dictionary<string, object>
            {
                {"1", "1"},
                {"2", 2},
                {"3", false},
            };

            await vaultClient.WriteSecretAsync(path, secretData);

I am getting an issue at line where we try to write the data to the path await vaultClient.WriteSecretAsync(path, secretData); 

as below.

at VaultSharp.VaultClient.<MakeVaultApiRequest>d__129`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at VaultSharp.VaultClient.<MakeVaultApiRequest>d__128.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at VaultSharp.VaultClient.<WriteSecretAsync>d__47.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Vault.Program.<process>d__4.MoveNext() in c:\Users\kkumar\Documents\Visual Studio 2013\Projects\Vault\Vault\Program.cs:line 35

Can you please suggest if Iam missing something here? We would want to use Vault to hold the AWS credentials. Can you please help?

**Comment by rajanadar** [comment]
hi @nkiranakumar 

thank you for using the library.

you are getting a null reference, because your **authenticationInfo** object is null when you initialize the IVaultClient. Authentication Info can be null, only when you're working with anonymous Vault APIs. i.e. Vault operations that don't need any credentials..

e.g. Initialize, GetSealStatus, Unseal, GetCACert etc..

In your case, WriteSecretAsync is an operation that needs a client token.. i.e. It is not an anonymous Vault Operation and needs some sort of token.

You can easily generate this token by initializing your vaultClient with a valid authenticationInfo object.

e.g.

```
IVaultClient vaultClient = VaultClientFactory.CreateVaultClient(new Uri("http://127.0.0.1:8200"),
authenticationInfo: new TokenAuthenticationInfo("vaultToken"));
```

you can also use

```
AppIdAuthenticationInfo
GitHubAuthenticationInfo
LDAPAuthenticationInfo
CertificateAuthenticationInfo
```

please let me know if this solved your issue.

from my side, in one of my next releases, i'll fix the null reference exception and throw a better error message, which conveys the above details.

**Comment by nkiranakumar** [comment]
Hi Rajanadar,

Thanks for the reply.

I have changes the code as you suggested.

IVaultClient vaultClient = VaultClientFactory.CreateVaultClient(new Uri("http://127.0.0.1:8200"),
                    new TokenAuthenticationInfo("CreateToken"));

                var path = "cubbyhole/foo/Test4321";

                var secretData = new Dictionary<string, object>
                {
                    {"1", "1"},
                    {"2", 2},
                    {"3", false},
                };

                await vaultClient.WriteSecretAsync(path, secretData);

Iam now getting error as below as "An error occurred while sending the request.". 

stack trace below

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at VaultSharp.DataAccess.HttpDataAccessManager.<MakeRequestAsync>d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at VaultSharp.VaultClient.<MakeVaultApiRequest>d__129`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at VaultSharp.VaultClient.<MakeVaultApiRequest>d__128.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at VaultSharp.VaultClient.<WriteSecretAsync>d__47.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Vault.Program.<Process>d__4.MoveNext() in c:\Users\kkumar\Documents\Visual Studio 2013\Projects\Vault\Vault\Program.cs:line 35

Can you please help?

**Comment by rajanadar** [comment]
I am assuming that you used a valid token instead of "vaultToken". That is just a placeholder. 
Similarly are the AppId and UserId valid values pre-configured in Vault?

Only then, the calls would succeed.

Basically, this is how the flow is:

1. once you initialize Vault, you get a root token.
2. using the root token, you can generate other tokens/credentials with restricted permissions.
3. these credentials can then be used to perform operations.

so in your case, assuming you have the root token, here is how you can create an app-id based user, and then use the credential of that user to write the secret data.

```
            IAuthenticationInfo devRootTokenInfo = new TokenAuthenticationInfo("YOUR_ROOT_VAULT_TOKEN_HERE");
            var rootClient = VaultClientFactory.CreateVaultClient(_vaultUri, devRootTokenInfo);

            var path2 = "app-id";
            var prefix = "auth/" + path2;
            var appId = "testapp";
            var userId = "Kkumar";
         
            var appIdAuthBackend = new AuthenticationBackend
            {
                BackendType = AuthenticationBackendType.AppId,
                MountPoint = path2
            };

            // we are creating the appId and userId based credentials here
            await rootClient.EnableAuthenticationBackendAsync(appIdAuthBackend);
            await rootClient.WriteSecretAsync(prefix + "/map/app-id/" + appId, new Dictionary<string, object> { { "value", "root" }, { "display_name", appId } });
            await rootClient.WriteSecretAsync(prefix + "/map/user-id/" + userId, new Dictionary<string, object> { { "value", appId } });

             // now that the appId based credentials have been created, we can use that
             // to write our secret data.

            var appIdAuthenticationInfo = new AppIdAuthenticationInfo(path2, appId, userId);
            var appidClient = VaultClientFactory.CreateVaultClient(_vaultUri, appIdAuthenticationInfo);

            var path = "cubbyhole/foo/Test4321";

            var secretData = new Dictionary<string, object>
            {
             {"1", "1"},
             {"2", 2},
             {"3", false},
            };
   
            await appidClient.WriteSecretAsync(path, secretData);
```

There is also one more option, where you can just use the root token to write the secret. (not recommended for non-dev scenarios)

```
IVaultClient vaultClient = VaultClientFactory.CreateVaultClient(new Uri("http://127.0.0.1:8200"),
new TokenAuthenticationInfo("YOUR_ROOT_VAULT_TOKEN_HERE"));
```

**Comment by nkiranakumar** [comment]
Hi Rajnadar, 

Thanks for taking time out for the sample. Had few queries.

Can "YOUR_ROOT_VAULT_TOKEN_HERE" be a GUID, that we create as Guid.NewGuid().ToString()?

Tried this, 

var _vaultUri = "http://127.0.0.1:8200";
                IAuthenticationInfo devRootTokenInfo = new TokenAuthenticationInfo(Guid.NewGuid().ToString());
                var rootClient = VaultClientFactory.CreateVaultClient(new Uri(_vaultUri), devRootTokenInfo);

Is that ok, or How do i create a vault token to be passed  to TokenAuthenticationInfo?

**Comment by rajanadar** [comment]
hi @nkiranakumar 

A new GUID won't work as a root token. A Root token is something Vault gets initialized with.

It looks like you're doing some prototyping on your dev box.
In that case, when you run, 

`vault server -dev`

Vault will emit out the Unseal Key and a Root Token on the Console.

```
Unseal Key: 8f7e939d806468dd154869c6f7b7a00a935385157a37c2995c81b6eb67fdd558
Root Token: f54e3884-c062-a2de-8989-d10202dce49e
```

You need to use the root token value, your Vault system emits.
This root token has admin permissions on the Vault server. So you can either directly use that, or create restricted tokens based on this. For dev-only prototype, the root token is a quick way to verify things.

Please note that this is the dev way of doing it. In a production scenario, it needs to be way more secure than this.

**Comment by rajanadar** [comment]
hi @nkiranakumar 

did that solve your issue?

please let me know and i'll close the issue.

thanks,
Raja

**Comment by rajanadar** [comment]
closing this issue @nkiranakumar 

please let me know if any concerns.
